version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: devicedb
      MYSQL_USER: deviceuser
      MYSQL_PASSWORD: devicepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  device-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: